### ISSUE TITLE
add generate-playbook utility

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/errata-tool-ansible#161]
Most of our products' ET configurations were crafted by hand over the years. We need a tool that will interrogate the ET and write a playbook for a product, like [we have for koji](https://github.com/ktdreyer/koji-ansible/blob/master/utils/generate-playbook).

**Comment by simonbaird** [comment]
Agreed. Once we can "round-trip" configuration from Errata Tool, meaning dump it out, and read it back it in correctly, then existing ET product configuration can trivially become ansible managed.

**Comment by simonbaird** [comment]
We could also spin up a new ET instance and populate it with all product configuration intact and current, which would be useful for testing.

**Comment by ktdreyer** [comment]
From what I understand, @rhjostone has written most or all of this into a https://github.com/red-hat-storage/errata-tool CLI sub-command now.
