### ISSUE TITLE
Key error in diff _settings for text_only_advisories_require_dists

### ISSUE THREAD

**Issue by ian-panzica** [ktdreyer/errata-tool-ansible#211]
Noticed a key error when the errata_tool_product library tries to produce a diff with an existing product in errata tool stage that is missing the `text_only_advisories_require_dists` field during run mode. The field is included in the new configuration and is missing in ET. Expected behavior would be to show a diff that shows that field as being added.

**Comment by ktdreyer** [comment]
Here's the stack trace we're seeing:
```
  File "modules/errata_tool_product.py", line 429, in <module>
  File "modules/errata_tool_product.py", line 425, in main
  File "modules/errata_tool_product.py", line 419, in run_module
  File "modules/errata_tool_product.py", line 373, in ensure_product
  File "module_utils/common_errata_tool.py", line 204, in diff_settings
KeyError: 'text_only_advisories_require_dists'
```

**Comment by ktdreyer** [comment]
The (edited) extra vars sent to Ansible Tower:
```
{
    "errata_tool_url": "https://errata.stage.engineering.redhat.com/",
    "env": "stage",
    "task": "errata_product",
    "name": "Sample Product Name",
    "short_name": "RHPRODUCT",
    "description": "An RH Product",
    "bugzilla_product_name": "An RH Product",
    "valid_bug_states": [
	"VERIFIED",
	"MODIFIED",
	"POST"
    ],
    "active": true,
    "ftp_path": "",
    "ftp_subdir": "RHFOOBAR",
    "default_docs_reviewer": "username@redhat.com",
    "push_targets": [
	"cdn",
	"cdn_docker",
	"cdn_docker_stage",
	"cdn_stage",
	"ftp"
    ],
    "default_solution": "enterprise",
    "state_machine_rule_set": "Default",
    "move_bugs_on_qe": true,
    "text_only_advisories_require_dists": true,
    "exd_org_group": "Cloud",
}
```

**Comment by ktdreyer** [comment]
https://errata.devel.redhat.com/api/v1/products/<shortname> has a `text_only_advisories_require_dists` value.

https://errata.stage.engineering.redhat.com/api/v1/products/<shortname> no longer has a `text_only_advisories_require_dists` value.

**Comment by simonbaird** [comment]
It's related to https://issues.redhat.com/browse/CWFENGINE-381 .

**Comment by ktdreyer** [comment]
We discussed in chat. Since the ET will soon drop that text_only_advisories_require_dists parameter, we're going to edit errata-tool-ansible to make `text_only_advisories_require_dists` a no-op parameter. Playbooks will continue to function without errors.

**Comment by ktdreyer** [comment]
This is resolved in release 0.0.208 on Ansible Galaxy. Thank you @simonbaird 

I've added an integration test to exercise `text_only_advisories_require_dists` in https://github.com/ktdreyer/errata-tool-ansible/pull/214 so we ensure playbooks continue to work if playbook authors have set that parameter explicitly.

Please do remove this parameter from future playbooks, though.

**Comment by simonbaird** [comment]
It's possible we might break other systems similarly using the products API. In hindsight, we could have made ET strip the unused field. I'll create a Jira to track that idea, just in case we need to address it quickly tomorrow.

**Comment by simonbaird** [comment]
See https://issues.redhat.com/browse/CWFENGINE-419 .
