### ISSUE TITLE
GitHub Actions not uploading new collections to galaxy.ansible.com

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/errata-tool-ansible#308]
GitHub fails to push the latest `master` branch (version `0.0.319`, includes https://github.com/ktdreyer/errata-tool-ansible/pull/306) to [Ansible Galaxy](https://galaxy.ansible.com/ui/repo/published/ktdreyer/errata_tool_ansible/). ansible-8.4.0 currently fails like so:

```
+ ansible-galaxy collection build
Created collection for ktdreyer.errata_tool_ansible at /home/runner/work/errata-tool-ansible/errata-tool-ansible/_build/ktdreyer-errata_tool_ansible-0.0.319.tar.gz
ERROR! Error when finding available api versions from default (https://galaxy.ansible.com/) (HTTP Code: 403, Message: Forbidden)
```

The Ansible team has performed a large upgrade this week ([AAH-2737](https://issues.redhat.com/browse/AAH-2737)). It's unclear if my existing `GALAXY_API_KEY` will continue to work, or if I should regenerate that and [set it again](https://github.com/ktdreyer/errata-tool-ansible/settings/secrets/actions).

**Comment by CryptoRodeo** [comment]
Any updates on this issue? It looks like there might be some more requests coming to this module from HoneyBadger: CWFCONF-5591

**Comment by ktdreyer** [comment]
I've reset the API key, and GitHub Actions still shows the same error. Maybe there's something else I'm missing.

**Comment by CryptoRodeo** [comment]
@ktdreyer thanks for the update. For now I was able to get around not being able to pull the latest change by specifying that the collections should be pulled with git. See CWFCONF-5617 for the work around details

**Comment by ktdreyer** [comment]
Thanks for the update.

I tried uploading directly from my laptop, same problem. I also tried uploading directly via the web UI, and that shows me "You don't have rights to do this operation."

**Comment by ktdreyer** [comment]
I've opened https://forum.ansible.com/t/cannot-upload-to-ktdreyer-galaxy-namespace/1702 , ideally this gets linked back into AAH-2737

**Comment by ktdreyer** [comment]
An Ansible engineer resolved this for me, and Ansible Galaxy has the latest version now (`0.0.320`)
