### ISSUE TITLE
bug: errata_tool_user doesn't require organization variable but if it is not specified it doesn't work

### ISSUE THREAD

**Issue by pbortlov** [ktdreyer/errata-tool-ansible#58]
Hello,
there is not required `organization` variable in `errata_tool_user` module but if it is not used it returns error `The error was: ValueError: {'error': "Couldn't find UserOrganization with 'id'="}`.

**Comment by ktdreyer** [comment]
I'm not able to reproduce this in an Errata Tool dev environment where I load all the fixtures. The default `UserOrganization` is "Engineering" when I omit the parameter in the UI or the REST API.

Did you populate the user_organizations table with `test/fixtures/user_organizations.yml`?

**Comment by ktdreyer** [comment]
We looked at `app/models/user.rb` in errata-rails.git.

It has a `before_create` method, with the following snippet (added 2009):

```ruby
unless self.organization
  self.organization = UserOrganization.find_by_name('Engineering')
end
```

It's a little strange that the server would say "Couldn't find UserOrganization with 'id'="", specifically ActiveRecord should be searching the user_organizations table by "name" not "id", but maybe that's a quirk of how ActiveRecord searches.

@pbortlov will try to reproduce
