### ISSUE TITLE
errata_tool_variant: rhel_variant shouldn't be required

### ISSUE THREAD

**Issue by pbortlov** [ktdreyer/errata-tool-ansible#76]
Hello,

if rhel_variant is required it is not possible to create a brand new variant. To create a new variant is mention in documentation and it works through the API. https://errata.devel.redhat.com/developer-guide/api-http-api.html#api-variants

**Comment by ktdreyer** [comment]
Would you please your full `errata_tool_variant` task? I'm wondering if this has something to do with the product or product version.

**Comment by pbortlov** [comment]
Hello Ken,

as we discussed today.
Proposing solution: don’t send “rhel_variant” at all if the user does not specify it. Make this field optional.

Pavlina
