### ISSUE TITLE
errata_tool_product: the readme doc variables for the product module is not the same in code

### ISSUE THREAD

**Issue by pbortlov** [ktdreyer/errata-tool-ansible#77]
Hi,

I found that there is inconsistency between README doc variables and variables specified in the mode errata_tool_product. 
README doc _bugzilla_product_name_ : errata_tool_product code _bugzilla_product_
README doc _Valid_bug_states_ : errata_tool_product code _bugzilla_states_

**Comment by ktdreyer** [comment]
Thanks! I fixed `bugzilla_product_name` here: https://github.com/ktdreyer/errata-tool-ansible/pull/83

I noticed a few other bugs in `valid_bug_states`, so I fixed those in https://github.com/ktdreyer/errata-tool-ansible/pull/85
